"use client";

import { FormEvent, ReactNode, useEffect, useState } from "react";

type Identity = { tenant_id: string; subject: string; roles: string[] };
type Overview = { tenant_id: string; tasks: number; pending_approvals: number; active_aras: number; failed_jobs: number; artifacts_enabled: boolean; qdrant_enabled: boolean; model_backend: string; sandbox_enabled: boolean; sandbox_timeout_seconds: number };
type Operations = { tasks: Record<string, unknown>[]; approvals: Record<string, unknown>[]; remote_agents: Record<string, unknown>[]; jobs: Record<string, unknown>[]; memories: Record<string, unknown>[]; events: Record<string, unknown>[]; artifacts: Record<string, unknown>[] };

const apiUrl = process.env.NEXT_PUBLIC_ASTRA_AGENT_URL ?? "http://127.0.0.1:8000";
const tabs = ["overview", "approvals", "remote agents", "memory", "jobs", "audit", "artifacts"];
const value = (item: Record<string, unknown>, key: string) => String(item[key] ?? "");

function Pill({ children, tone = "neutral" }: Readonly<{ children: ReactNode; tone?: string }>) { return <span className={`pill ${tone}`}>{children}</span>; }

export default function Console() {
  const [token, setToken] = useState(""); const [identity, setIdentity] = useState<Identity>(); const [overview, setOverview] = useState<Overview>(); const [operations, setOperations] = useState<Operations>(); const [active, setActive] = useState("overview"); const [error, setError] = useState(""); const [busy, setBusy] = useState("");
  const headers = { Authorization: `Bearer ${token}`, "Content-Type": "application/json" };
  async function load(nextToken = token) { const head = { Authorization: `Bearer ${nextToken}` }; const [me, status, ops] = await Promise.all([fetch(`${apiUrl}/api/v1/admin/me`, { headers: head }), fetch(`${apiUrl}/api/v1/admin/overview`, { headers: head }), fetch(`${apiUrl}/api/v1/admin/operations`, { headers: head })]); if (!me.ok || !status.ok || !ops.ok) throw new Error("Access denied. Use an OIDC token with an Astra operator role."); setIdentity(await me.json()); setOverview(await status.json()); setOperations(await ops.json()); }
  async function connect(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); try { await load(); } catch (failure) { setError(failure instanceof Error ? failure.message : "Unable to connect"); } }
  async function action(path: string, payload?: Record<string, unknown>) { setBusy(path); try { const response = await fetch(`${apiUrl}/api/v1/admin${path}`, { method: "POST", headers, body: payload ? JSON.stringify(payload) : undefined }); if (!response.ok) throw new Error("Action was rejected by the control plane."); await load(); } catch (failure) { setError(failure instanceof Error ? failure.message : "Action failed"); } finally { setBusy(""); } }
  async function download(artifact: Record<string, unknown>) { setBusy(value(artifact, "id")); try { const response = await fetch(`${apiUrl}/api/v1/artifacts/${value(artifact, "id")}/download`, { method: "POST", headers }); if (!response.ok) throw new Error("Artifact download unavailable"); window.open((await response.json()).download_url, "_blank", "noopener,noreferrer"); } catch (failure) { setError(failure instanceof Error ? failure.message : "Download failed"); } finally { setBusy(""); } }
  useEffect(() => { if (!token || !identity) return; const interval = window.setInterval(() => { void load().catch(() => undefined); }, 15000); return () => window.clearInterval(interval); }, [token, identity]);
  if (!identity || !overview || !operations) return <main className="sign-in"><section className="sign-in-card"><img src="/astra-agent.png" alt="Astra Agent" className="logo" /><p className="kicker">ASTRA CONTROL PLANE</p><h1>Operator workspace</h1><p>Use an OIDC access token. Authorization is enforced by Astra Agent, never by this browser.</p><form onSubmit={connect}><label>Access token<textarea value={token} onChange={(event) => setToken(event.target.value)} placeholder="Paste a bearer token" required /></label><button>Open console <span>→</span></button>{error && <output>{error}</output>}</form></section></main>;
  const loadedOperations = operations; const pending = loadedOperations.approvals.filter((item) => value(item, "state") === "pending"); const candidates = loadedOperations.memories.filter((item) => value(item, "state") === "candidate"); const metrics = [["Tasks", overview.tasks, "All delegated and local activity"], ["Approval queue", pending.length, "Commands and impactful actions"], ["Connected ARAs", overview.active_aras, "Trusted remote agents"], ["Job failures", overview.failed_jobs, "Durable pipeline exceptions"]];
  function Table({ children }: Readonly<{ children: ReactNode }>) { return <div className="table-wrap"><table>{children}</table></div>; }
  function Workstream({ currentOverview }: Readonly<{ currentOverview: Overview }>) { const overview = currentOverview; const operations = loadedOperations; if (active === "overview") return <section className="content-grid"><article className="panel posture"><div className="panel-heading"><div><p className="kicker">RUNTIME POSTURE</p><h2>Control plane services</h2></div><button className="icon-button" onClick={() => void load()}>↻</button></div><div className="service-list"><div><span>Model provider</span><strong>{overview.model_backend}</strong><Pill tone="success">Available</Pill></div><div><span>Vector retrieval</span><strong>{overview.qdrant_enabled ? "Qdrant" : "Local ranking"}</strong><Pill tone={overview.qdrant_enabled ? "success" : "neutral"}>{overview.qdrant_enabled ? "Enabled" : "Fallback"}</Pill></div><div><span>Artifact store</span><strong>{overview.artifacts_enabled ? "S3 compatible" : "Not configured"}</strong><Pill tone={overview.artifacts_enabled ? "success" : "neutral"}>{overview.artifacts_enabled ? "Enabled" : "Disabled"}</Pill></div></div></article><article className="panel execution"><div className="panel-heading"><div><p className="kicker">EXECUTION GUARDRAILS</p><h2>Sandbox policy</h2></div><Pill tone={overview.sandbox_enabled ? "success" : "neutral"}>{overview.sandbox_enabled ? "Protected" : "Off"}</Pill></div><div className="sandbox-mark">⌘</div><p>Commands require explicit approval, then run in an isolated, read-only workspace.</p><dl><dt>Runtime limit</dt><dd>{overview.sandbox_timeout_seconds} seconds</dd><dt>Network</dt><dd>Disabled</dd><dt>Workspace</dt><dd>Read only</dd></dl></article></section>;
    if (active === "approvals") return <article className="panel work-panel"><div className="panel-heading"><div><p className="kicker">DECISION QUEUE</p><h2>Approvals awaiting a decision</h2></div><Pill tone="amber">{pending.length} pending</Pill></div><Table><thead><tr><th>Capability</th><th>Reason</th><th>Requested</th><th>Decision</th></tr></thead><tbody>{pending.map((item) => <tr key={value(item,"id")}><td><strong>{value(item,"capability") ? value(item,"capability").replace(/\[object Object\]/, "Scoped capability") : "Scoped capability"}</strong></td><td>{value(item,"reason")}</td><td>{new Date(value(item,"created_at")).toLocaleString()}</td><td><button disabled={busy.includes(value(item,"id"))} className="small-button approve" onClick={() => void action(`/approvals/${value(item,"id")}/decision`, { tenant_id: overview.tenant_id, granted: true })}>Grant</button><button disabled={busy.includes(value(item,"id"))} className="small-button deny" onClick={() => void action(`/approvals/${value(item,"id")}/decision`, { tenant_id: overview.tenant_id, granted: false })}>Deny</button></td></tr>)}{!pending.length && <tr><td colSpan={4} className="empty">No approvals waiting.</td></tr>}</tbody></Table></article>;
    if (active === "remote agents") return <article className="panel work-panel"><div className="panel-heading"><div><p className="kicker">REMOTE EXECUTION</p><h2>Registered ARAs</h2></div><Pill>{operations.remote_agents.length} total</Pill></div><Table><thead><tr><th>Agent</th><th>Status</th><th>Trust</th><th>Last seen</th></tr></thead><tbody>{operations.remote_agents.map((item) => <tr key={value(item,"id")}><td><strong>{value(item,"name")}</strong><small>{value(item,"runtime_version")}</small></td><td><Pill tone={value(item,"status") === "active" ? "success" : "neutral"}>{value(item,"status")}</Pill></td><td>{value(item,"trust_level")}</td><td>{new Date(value(item,"last_seen_at")).toLocaleString()}</td></tr>)}{!operations.remote_agents.length && <tr><td colSpan={4} className="empty">No remote agents are registered for this tenant.</td></tr>}</tbody></Table></article>;
    if (active === "memory") return <article className="panel work-panel"><div className="panel-heading"><div><p className="kicker">MEMORY REVIEW</p><h2>Candidate memories</h2></div><Pill tone="amber">{candidates.length} pending</Pill></div><div className="memory-list">{candidates.map((item) => <div className="memory-card" key={value(item,"id")}><div><Pill>{value(item,"kind")}</Pill><p>{value(item,"content")}</p><small>Confidence {Number(item.confidence ?? 0).toFixed(2)}</small></div><div><button className="small-button approve" onClick={() => void action(`/memories/${value(item,"id")}/review`, { tenant_id: overview.tenant_id, promote: true })}>Promote</button><button className="small-button deny" onClick={() => void action(`/memories/${value(item,"id")}/review`, { tenant_id: overview.tenant_id, promote: false })}>Reject</button></div></div>)}{!candidates.length && <p className="empty">No candidate memories require review.</p>}</div></article>;
    if (active === "jobs") return <article className="panel work-panel"><div className="panel-heading"><div><p className="kicker">DURABLE PIPELINE</p><h2>Background jobs</h2></div><Pill>{operations.jobs.length} tracked</Pill></div><Table><thead><tr><th>Kind</th><th>State</th><th>Attempts</th><th>Last error</th></tr></thead><tbody>{operations.jobs.map((item) => <tr key={value(item,"id")}><td>{value(item,"kind")}</td><td><Pill tone={value(item,"state") === "failed" ? "rose" : value(item,"state") === "completed" ? "success" : "amber"}>{value(item,"state")}</Pill></td><td>{value(item,"attempt_count")}</td><td>{value(item,"last_error") || "-"}</td></tr>)}</tbody></Table></article>;
    if (active === "audit") return <article className="panel work-panel"><div className="panel-heading"><div><p className="kicker">APPEND-ONLY RECORD</p><h2>Recent audit events</h2></div><Pill>{operations.events.length} events</Pill></div><Table><thead><tr><th>Event</th><th>Actor</th><th>When</th><th>Task</th></tr></thead><tbody>{operations.events.slice(-30).reverse().map((item) => <tr key={value(item,"id")}><td><strong>{value(item,"event_type")}</strong></td><td>{value(item,"actor_type")}</td><td>{new Date(value(item,"occurred_at")).toLocaleString()}</td><td><code>{value(item,"task_id").slice(0,8) || "-"}</code></td></tr>)}</tbody></Table></article>;
    return <article className="panel work-panel"><div className="panel-heading"><div><p className="kicker">ARTIFACT STORE</p><h2>Authorized artifacts</h2></div><Pill>{operations.artifacts.length} available</Pill></div><Table><thead><tr><th>Name</th><th>Type</th><th>Size</th><th /></tr></thead><tbody>{operations.artifacts.map((item) => <tr key={value(item,"id")}><td><strong>{value(item,"name")}</strong></td><td>{value(item,"media_type")}</td><td>{value(item,"size_bytes")} bytes</td><td><button className="small-button" onClick={() => void download(item)}>Download</button></td></tr>)}{!operations.artifacts.length && <tr><td colSpan={4} className="empty">No artifacts are available.</td></tr>}</tbody></Table></article>; }
  return <div className="workspace-shell"><aside className="app-rail"><img src="/astra-agent.png" alt="Astra Agent" className="rail-logo" /><div className="rail-rule" /><button className="rail-icon active">⌘</button><button className="rail-icon">◌</button><button className="rail-icon">⚙</button></aside><aside className="command-rail open"><div className="rail-heading"><span>Operations</span></div><div className="operator"><span className="operator-avatar">{identity.subject.slice(0,1).toUpperCase()}</span><div><strong>{identity.subject}</strong><small>{identity.roles.join(" · ")}</small></div></div><nav>{tabs.map((tab) => <button key={tab} className={active === tab ? "nav-item selected" : "nav-item"} onClick={() => setActive(tab)}><span>{tab === "overview" ? "▦" : tab === "approvals" ? "✓" : tab === "remote agents" ? "◉" : tab === "memory" ? "◇" : tab === "jobs" ? "⌁" : tab === "audit" ? "◫" : "↓"}</span>{tab}{tab === "approvals" && pending.length > 0 && <b>{pending.length}</b>}</button>)}</nav><div className="rail-note"><p className="kicker">TENANT</p><code>{overview.tenant_id}</code></div></aside><main className="dashboard"><header className="dashboard-header"><div><p className="kicker">ASTRA / OPERATOR CONSOLE</p><h1>Control plane</h1><p>Live operations, bounded execution, and auditable decisions.</p></div><div className="header-actions"><span className="live-dot">Live</span><button className="outline-button" onClick={() => void load()}>Refresh</button></div></header><div className="segmented-tabs">{tabs.map((tab) => <button key={tab} className={active === tab ? "tab active" : "tab"} onClick={() => setActive(tab)}>{tab}</button>)}</div>{active === "overview" && <section className="metrics">{metrics.map(([label,count,note]) => <article className="metric-card" key={String(label)}><div className="metric-top"><span>{label}</span><i>↗</i></div><strong>{count}</strong><small>{note}</small></article>)}</section>}{error && <output className="toast-error">{error}</output>}<Workstream currentOverview={overview} /></main></div>;
}
